### ISSUE TITLE
Weather is broken

### ISSUE THREAD

**Issue by alexanderepstein** [chubin/wttr.in#136]
Running ```curl wttr.in``` either produces one of two outputs at the moment ```ERROR``` or just the bottom tag line ```New feature: multilingual location names wttr.in/станция+Восток (in UTF-8) and location search wttr.in/~Kilimanjaro (just add ~ before)
Follow @igor_chubin for wttr.in updates```

**Comment by freude** [comment]
i have got same issue

**Comment by chubin** [comment]
Fixed!
Guys sorry for the downtime, and thank you for reporting

**Comment by alexanderepstein** [comment]
I am still having the same issue, do new changes immediately push up to the website?

**Comment by chubin** [comment]
It is probably a caching issue, please check it once again

**Comment by alexanderepstein** [comment]
> Running with wget gave me a bit more info 
```bash
Resolving wttr.in (wttr.in)... 5.9.243.177
Connecting to wttr.in (wttr.in)|5.9.243.177|:80... connected.
HTTP request sent, awaiting response... 502 Bad Gateway
2017-07-25 04:58:21 ERROR 502: Bad Gateway.
```

Was just about to comment that, went to run wget one more time and now it works thanks :smile:
