### ISSUE TITLE
png output has wrong location

### ISSUE THREAD

**Issue by elias-boemeke** [chubin/wttr.in#311]
Hi,

I live in Germany and have the problem that the png output uses the wrong location.
More precisely, 'wttr.in' outputs weather for the correct location Göttingen, while
'wttr.in/.png' shows the weather for Nuremberg, which is a few hundert kilometers away.

I know I can get the weather for Göttingen by using the query 'wttr.in/göttingen.png' but
I'd like my scripts to be independent from location.

**Comment by Rezn1** [comment]
When .png option is present location seems to always default to Nuremberg, Germany.
I don't even live in Germany and the same thing happens to me.

Also .png appears to override language passed in third-level domain. E.g. wttr.in/_lang=fr.png is in French, but fr.wttr.in/.png is in English.

**Comment by chubin** [comment]
@elias-boemeke @Rezn1 Thank you very much for reporting it.
There were several problems indeed, but I hope they are fixed now.

1. Both `MyLocation.png` and `.png` should show weather in your location (the `MyLoaction.png` form has no other advantages than just the one that the returned file has some normal name).
2. `LANG.wttr.in` queries work for PNG-queries as they should.
3. (you did not report it, but I knew that this problem existed) Query options were ignored: i.e. `/Berlin.png?lang=de` and the only to pass the options was to use the underscore form: `Berling_lang=de.png`

All of these problems is fixed now. Please test, whether it works for you now. And once again thank you for reporting

**Comment by elias-boemeke** [comment]
@chubin Thanks for your answer.
Unfortunately i am still encountering unexpected behaviour.
`http://wttr.in/.png` still has Nuremberg as location:

![image](https://user-images.githubusercontent.com/51261999/60774787-c56cb180-a119-11e9-8484-226ed48f5e9f.png)

and `http://wttr.in/_qpF.png` fails with an error:

![image](https://user-images.githubusercontent.com/51261999/60774789-d87f8180-a119-11e9-8594-aa9e1a40dab7.png)

**Comment by Rezn1** [comment]
@chubin 2. and 3. are resolved but 1. still persist.

By the way `get_location` is only called in `location_processing` which is only called in `wttr` ( `wttr.in/lib/wttr_srv.py` ) in `if not png_filename:`
I only skimmed the code, so sorry if I'm wrong.

**Comment by chubin** [comment]
@elias-boemeke @Rezn1 Thank you guys, after the comment of Elias I've spotted the problem. I will fix it tonight

**Comment by chubin** [comment]
@elias-boemeke @Rezn1 Please test it again. I think, I've fixed it.
That is what I get when running it from Ireland:

![MyLocation](https://user-images.githubusercontent.com/3875145/60832010-357f4400-a1bb-11e9-9d31-e1631d9326b2.png)

**Comment by Rezn1** [comment]
@chubin works perfectly.

**Comment by elias-boemeke** [comment]
@chubin Thanks,
`curl wttr.in/.png` now works perfectly.

However applying png-options still is broken for me:
For example `curl wttr.in/_0.png` outputs
![image](https://user-images.githubusercontent.com/51261999/60848608-8f95fe80-a1e7-11e9-9c6c-00de7c956488.png)
