### ISSUE TITLE
BUG: Unknown location page is not displayed for some unknown locations

### ISSUE THREAD

**Issue by chubin** [chubin/wttr.in#500]
See #477 for example

**Comment by iago-lito** [comment]
Oh, is this not a problem to be reported upstream?

Btw, I find the unknown location text real fun, but not highlighted enough. I only came accross it twice, but I twice had to figure out that the location was wrong *based on the weather inconsistencies* and not the actual text X)

```
We were unable to find your location
so we have brought you to Oymyakon,
one of the coldest permanently inhabited locales on the planet.
```

Maybe it would have been clearer if the text had been highlighted red like an error, or at least decorated with little warning signs? `⚠ ⚠ ⚠`

**Comment by chubin** [comment]
> Oh, is this not a problem to be reported upstream?

No, it is our bug. wttr.in handles locations on its own,
because location handling by weather data sources is usually pretty bad.
They expect location names in one language (or some distinct languages)
only; they don't allow location names like `Eiffel tower` etc.

>  I find the unknown location text real fun, but not highlighted enough

Yes, agree. I already thought about it too. Maybe background?

**Comment by iago-lito** [comment]
Yes, I think background could be good, because it is unusual to have different background color, so it would be noticed.

This said, it *could* display weirdly depending on the user terminal config. If it turns out to be ugly, maybe an alternate solution is to just make the text red (foreground)? This may also be visible enough because it already spans several lines.

**Comment by chubin** [comment]
New 404 page design:

```
$ curl fr.wttr.in/xxxxxsdd
```
![Selection_087](https://user-images.githubusercontent.com/3875145/103459587-de572280-4d10-11eb-926b-f70cbdd950bb.png)

**Comment by chubin** [comment]
@iago-lito It is fixed now, please test

**Comment by iago-lito** [comment]
@chubin Nice :) This is much easier to notice! (funny how it's difficult to trigger 404, anything I type seems to be pointing somewhere on Earth X)

I'm still getting the following with v2 though, but I suspect you are already aware:

![v2 404](https://user-images.githubusercontent.com/10091387/103535952-f0140380-4e91-11eb-832e-543dfbfbcafb.png)

**Comment by chubin** [comment]
Yes, I know, this must be fixed too, but keep in mind that even in this case status code is 404:

```
$ curl -I fr.wttr.in/asdfsadfsafsafsadf?view=v2
HTTP/1.1 404 Not Found
Server: nginx/1.10.3
Date: Mon, 04 Jan 2021 12:46:20 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 10489
Connection: keep-alive
Access-Control-Allow-Origin: *
```

(in future, I would like to use `format` for formats (PNG, ANSI, HTML, etc.),
and `view` for views (v1, v2, v3, j1, "format-line"; the latter, the word "format" in "forma line" is exactly the reason of this ambiguity, but anyway you can already use `view=` for that)
